name: '522'
channels:
  - conda-forge
dependencies:
  - ucimlrepo=0.0.7
  - ipykernel=7.1.0
  - ydata-profiling
  - pandas=2.3.3
  - altair=6.0.0
  - jupyterlab=4.5.0
  - ipywidgets=8.1.8
  - python=3.11
  - scikit-learn=1.7.2
  - pandera=0.27.0
  - dask=2025.11.0
  - vl-convert-python=1.8.0
  - click=8.1.8
  - quarto=1.8.26
